CREATE TABLE "GIS_DS"."PROPERTIES_EXT" 
(
  "OBJECTID" NUMBER(*,0) NOT NULL ENABLE, 
  "PARCEL_NUMBER" NVARCHAR2(9), 
  "LOCATION" NVARCHAR2(25), 
  "OWNER_1" NVARCHAR2(25), 
  "OWNER_2" NVARCHAR2(25), 
  "CENSUS_TRACT" NVARCHAR2(3), 
  "ZIP_CODE" NVARCHAR2(5), 
  "GEOGRAPHIC_WARD" NUMBER(2,0), 
  "STREET_CODE" NUMBER(5,0), 
  "HOUSE_NUMBER" NUMBER(5,0), 
  "SUFFIX" NVARCHAR2(1), 
  "UNIT" NVARCHAR2(7), 
  "HOUSE_EXTENSION" NUMBER(4,0), 
  "RECORDING_DATE" DATE, 
  "SALE_DATE" DATE, 
  "SALE_PRICE" NUMBER(11,2), 
  "UNFINISHED" NVARCHAR2(1), 
  "ASSESSMENT_DATE" DATE, 
  "MARKET_VALUE_DATE" DATE, 
  "MARKET_VALUE" NUMBER(11,2), 
  "TAXABLE_LAND" NUMBER(11,2), 
  "TAXABLE_BUILDING" NUMBER(11,2), 
  "EXEMPT_LAND" NUMBER(11,2), 
  "EXEMPT_BUILDING" NUMBER(11,2), 
  "CATEGORY_CODE" NUMBER(1,0), 
  "CATEGORY_CODE_DESCRIPTION" NVARCHAR2(64),
  "ZONING" NVARCHAR2(5), 
  "SITE_TYPE" NVARCHAR2(1), 
  "FRONTAGE" NUMBER(16,4), 
  "DEPTH" NUMBER(16,4), 
  "PARCEL_SHAPE" NVARCHAR2(1), 
  "TOTAL_AREA" NUMBER(11,2), 
  "TOPOGRAPHY" NVARCHAR2(1), 
  "GARAGE_TYPE" NVARCHAR2(1), 
  "GARAGE_SPACES" NUMBER(2,0), 
  "OFF_STREET_OPEN" NUMBER(2,0), 
  "VIEW_" NVARCHAR2(1), 
  "OTHER_BUILDING" NVARCHAR2(1), 
  "NUMBER_STORIES" NUMBER(3,1), 
  "GENERAL_CONSTRUCTION" NVARCHAR2(1), 
  "TYPE_DWELLING" NVARCHAR2(1), 
  "DATE_EXTERIOR_CONDITION" DATE, 
  "EXTERIOR_CONDITION" NVARCHAR2(1), 
  "QUALITY_GRADE" NVARCHAR2(1), 
  "YEAR_BUILT" NUMBER(4,0), 
  "YEAR_BUILT_ESTIMATE" NVARCHAR2(1), 
  "NUMBER_OF_ROOMS" NUMBER(3,1), 
  "NUMBER_OF_BEDROOMS" NUMBER(3,1), 
  "NUMBER_OF_BATHROOMS" NUMBER(3,1), 
  "BASEMENTS" NVARCHAR2(1), 
  "FIREPLACES" NUMBER(2,0), 
  "TYPE_HEATER" NVARCHAR2(1), 
  "FUEL" NVARCHAR2(1), 
  "CENTRAL_AIR" NVARCHAR2(1), 
  "INTERIOR_CONDITION" NVARCHAR2(1), 
  "UTILITY" NVARCHAR2(1), 
  "SEWER" NVARCHAR2(1), 
  "SEPARATE_UTILITIES" NVARCHAR2(1), 
  "TOTAL_LIVABLE_AREA" NUMBER(5,0), 
  "BOOK_AND_PAGE" NVARCHAR2(7), 
  "REGISTRY_NUMBER" NVARCHAR2(15), 
  "CROSS_REFERENCE" NVARCHAR2(9), 
  "SHAPE" "SDE"."ST_GEOMETRY" 
)
ORGANIZATION EXTERNAL 
(
  TYPE ORACLE_LOADER
  DEFAULT DIRECTORY "GIS_DIR"
  ACCESS PARAMETERS
  (
    RECORDS DELIMITED BY NEWLINE
    FIELDS TERMINATED BY ','
    OPTIONALLY ENCLOSED BY '"'
    MISSING FIELD VALUES ARE NULL
    (
    )
  )
  LOCATION ('properties.csv')
);