CREATE TABLE "GIS_DS"."STCODE_EXT" 
(
  "OBJECTID" NUMBER(*,0) NOT NULL ENABLE, 
  "STCODE" NUMBER(5,0) NOT NULL ENABLE, 
  "STNAME" NVARCHAR2(50) NOT NULL ENABLE, 
  "DIR" NVARCHAR2(3), 
  "DSG" NVARCHAR2(10), 
  "FILL" NUMBER(5,0), 
  "RELLOC" NVARCHAR2(150), 
  "FULL_NAME" NVARCHAR2(100)
)
ORGANIZATION EXTERNAL 
(
  TYPE ORACLE_LOADER
  DEFAULT DIRECTORY "GIS_DIR"
  ACCESS PARAMETERS
  (
    RECORDS DELIMITED BY NEWLINE
    SKIP 1
    FIELDS TERMINATED BY ','
    OPTIONALLY ENCLOSED BY '"'
    MISSING FIELD VALUES ARE NULL
    (
      STCODE,
      STNAME,
      DIR,
      DSG,
      FILL,
      RELLOC,
      FULL_NAME
    )
  )
  LOCATION ('street_codes.csv')
);
